### ISSUE TITLE
Inactivity Monitor - Can´t select role with @role

### ISSUE THREAD

**Issue by Shiro-chan7** [ComputerMaster1st/Railgun#29]
Cant select the inactivity role with the rgimon role @role command.
Error: Unable to find role: @Inaktiv

**Comment by ComputerMaster1st** [comment]
Hi There,

It appears the mentioning might be conflicting with another parameter. I'll do a code check to see what's going on.

**Comment by ComputerMaster1st** [comment]
This should be fixed now. Re-open if it's still an issue. :)
