### ISSUE TITLE
Certain song for autojoin?

### ISSUE THREAD

**Issue by NateDogge** [ComputerMaster1st/Railgun#36]
with the auto join feature, is their a way to have different songs for different people? for example if person A joins it plays song 1, if person B joins it plays song 2. Thanks

**Comment by ComputerMaster1st** [comment]
Hi There,

At this time, there's no command available to do that. However, I could add it in though. May I ask why you'd like this feature please?

**Comment by ComputerMaster1st** [comment]
Hi There,

Closing issue as this is now linked to #40
