### ISSUE TITLE
Feature Request: Custom auto-join

### ISSUE THREAD

**Issue by PandaPandemic** [ComputerMaster1st/Railgun#40]
Allows us to set a custom playlist or song for auto-join to play instead of the predefined one.

**Comment by ComputerMaster1st** [comment]
Hi There,

You'd like the Auto-Join to tell the player to play something specific when a user connects then carry on as normal afterwards? If that's the case, it should be quite easy to have the auto-join set a specific song at first. However, for a custom playlist... this'll require implementing multi-playlist support.

Multi-playlist support is something I'm hesitating to do as I have no clue on how I want the commands structured, etc. and the backend code will need to be overhauled to account for multi-playlists.

Regards, 

CM1

**Comment by PandaPandemic** [comment]
That, or have it play a youtube playlist for the auto-join.

**Comment by ComputerMaster1st** [comment]
Hi There,

Okay. If you're happy with just a specific song to play on auto-join, I'll go implement it since demand for multi-playlist support is very little at best as far as I know.

**Comment by PandaPandemic** [comment]
That would be perfect!

**Comment by ComputerMaster1st** [comment]
Hi There,

This has now been implemented. Refer to [rgmusic auto play](https://github.com/ComputerMaster1st/Railgun/wiki/Music:-Auto#rgmusic-auto-play-songid)
on our wiki to learn how to use this command.

Closing issue due to enhancement now implemented.

Regards,

CM1
