### ISSUE TITLE
Feature Request: Link chosen song with searched song request

### ISSUE THREAD

**Issue by Barinzaya** [ComputerMaster1st/Railgun#43]
When a search phrase is used to request a song, it would be nice if the song that was chosen would be linked in Railgun's response that the song was queued. In cases where song requests are made available to be used by anybody, this would make it easier to preview the songs that are placed in the queue in order to moderate the requests that are made. Currently, the actual YouTube name of the chosen song is included, but it has to be manually searched for to listen to it.

**Comment by ComputerMaster1st** [comment]
Hi There,

Are asking for YT links to be provided for songs that have been added to queue?

**Comment by Barinzaya** [comment]
Exactly. Right now it only lists the name, but it would be useful if it included the link as well.

**Comment by ComputerMaster1st** [comment]
Hi There,

Understood. That'll be really quick to implement.

**Comment by ComputerMaster1st** [comment]
Implemented in Commit eaf67985309d796b07aff6dc097f834d52c3e67b
