### ISSUE TITLE
Feature Request: Command to remove specific song from queue

### ISSUE THREAD

**Issue by Barinzaya** [ComputerMaster1st/Railgun#44]
It would be useful if there were a way to remove a song that was manually added to the queue. The closest equivalent right now is manually skipping it as soon as Railgun starts to play it, which requires additional attention.

**Comment by ComputerMaster1st** [comment]
Hi There,

This will be quite useful to have and I believe should be quite easy to implement. I'll create a branch & open a pull request for this.

**Comment by ComputerMaster1st** [comment]
Merged.
