### ISSUE TITLE
Audio Quality

### ISSUE THREAD

**Issue by Dhruvvvv5** [ComputerMaster1st/Railgun#50]
The audio quality of the bot is really bad..Its like its lagging a lot..A lot of cuts in voice..Really bad Audio quality ..Earlier everything was fine.but now suddenly this happened

**Comment by ComputerMaster1st** [comment]
Hi There,

Which voice region is your Discord set to and is the quality still bad now?

**Comment by ComputerMaster1st** [comment]
No longer an issue. Solved via Discord. :)
