### ISSUE TITLE
RST Import doesn't work

### ISSUE THREAD

**Issue by BwansArt** [ComputerMaster1st/Railgun#52]
My streamer friend has a community discord and we're using the Railgun Bot as a Random Fun Fact Bot, so we've been feeding it with a few random Fun Facts about her an her Team. Some of the Facts are rather private, aome have a bit of ba grammar and she's been getting more attention lately, so I decided to just get the list by using **rgrst list** and edit it. Now I used the **rgrst reset** to delete it and import the edited list with **rgrst import** and attaching the file, but I always get the message
"RST data file processed! Added 0 RST entries!"
Even though there's around 40 facts. What did I do wrong?

**Comment by BwansArt** [comment]
Apologies for Typing mistakes my Laptop isn't the newest so the keyboard lags a bit xD

**Comment by ComputerMaster1st** [comment]
Hi There,

Did you remember to use `rgrst export` first before doing anything? It should generate a `.railgun` file which can be used to import back into the same server or into another server.

**Comment by ComputerMaster1st** [comment]
If you still have the list, you can modify it to work with the import.

Here's an example of what the file looks like when opened in notepad. If you copy this layout and replace the msgs here with your own and save it as a `.railgun` file, you should be able to import it. If you're unsure how to do this, send me the list and I'll work my magic when able. :+1: 
```
# CryoDev Development Team's RST List.
# Generated At : 11/30/2020 5:26:30 PM
#
# !!! DO NOT CHANGE/MODIFY THIS FILE !!! 

>>>
Nyaaa~
<<<
>>>
Stop calling me bug zapper!
<<<
>>>
My name is Misaka Mikoto!
<<<
>>>
I decided to say something random. Here's your random... Random
<<<
>>>
here's a random message.
<<<
```

**Comment by BwansArt** [comment]
Ah thank you very much! I unfortunately found the export command after resetting ><
I thought about editing the now empty Railgun file, but I wasn't sure bc of the "Do not modify" warning. 
I'll try that out then, thank you!

**Comment by ComputerMaster1st** [comment]
Hi There,

No problem! ;)

That warning is there to ward off accidental changes. You can change it if you know how.

Just an off-topic note, I too also stream. Usually games though. I'm found at twitch.tv/nekoputervr.

Anyways, closing issue as this is now resolved.

**~Case Closed~**
