### ISSUE TITLE
Railgun Inserting Itself into bites

### ISSUE THREAD

**Issue by SirDurtle** [ComputerMaster1st/Railgun#54]
Railgun has a chance to be in the bite when someone types rgbite @mention.

So messages like "biter bit railgun" are common.
On my server, I have railgun nicknamed BB-8. I don't know if that would cause an issue, but it is something I've changed.

I don't know if this is intended, but it is annoying if you want the bite to be between just you and someone else.

**Comment by ComputerMaster1st** [comment]
Hi There,

This was the original intention to bring in pure randomness. I can implement an option to have the randomness for user choosing to be turned off if you wish.

**Comment by SirDurtle** [comment]
Sure! Sounds great.

Thanks for the quick response, and I also wanted to say that the bot itself is really very good and I'm surprised more people don't use it.

**Comment by ComputerMaster1st** [comment]
Hi There,

I'll start on this when I'm able to. I was pre-occupied with other things at the moment. I'll do it as quick as I can when I get the chance. I'll attach a pull request to this issue once I start on it. :)

**Comment by ComputerMaster1st** [comment]
All done! The command to turn off the randomness is `rgbite norandom`. Does require `Manage Messages` permission.
