### ISSUE TITLE
What appened with railgun?

### ISSUE THREAD

**Issue by sanslash332** [ComputerMaster1st/Railgun#62]
Why currently railgun is unavailable?

We have added railgun to our server a lot time ago and works fine, but afew days ago any command don't work on her, and She starts to send estrange messages about roblocks promo codes another stuff to the admins that we added her as a contact.

Where I can get news or information about the bot?
To wait when she returns to the normality.

Thanks for your development.

Waiting for news.

**Comment by ComputerMaster1st** [comment]
Hi There,

My Discord account got hijacked a few days ago and recovery is still ongoing with Discord Trust & Safety. I'm sorry for the issues this has caused.

We have a new Discord server (https://discord.gg/fFbMNGbXVv) and we've moved Railgun under a new bot account called Cryzen (https://discordapp.com/api/oauth2/authorize?client_id=890953679128100905&scope=bot). Your server configuration should be ok, however if it did leave your discord saying it was compromised, then the data may have been destroyed.

We had to self-destruct the bot to reduce the server count to reduce the amount of scams that are broadcasted by it. My twitter is https://www.twitter.com/Nekoputer so you can follow me there for any updates or you can join our discord.

Again, sorry for all the problems caused in regards to Railgun.

Regards,

ComputerMaster1st / Nekoputer

**Comment by sanslash332** [comment]
thanks @ComputerMaster1st for the fast answer!

OK, lets to add to the server the new account, and delete the old.

Thanks 😄 

I hope that the playlist its OK uwu.

      Thanks for your amazing job!
